### PR TITLE
fix: modify the customers service to work locally using a postgresql database

### PR DESCRIPTION
**Pull request by HarikrishnanBalagopal**
The instructions on the README.md are not working:
https://github.com/konveyor/mig-demo-apps/tree/7259959b620223494c84ac512760502be43b34af/apps/e2e-demo#running-locally
```
$ mvn clean spring-boot:run -P local
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 kB at 16 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (14 kB at 11 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.777 s
[INFO] Finished at: 2022-01-30T04:28:53+05:30
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "local" could not be activated because it does not exist.
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/user/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```
The sprint-boot maven plugin isn't present in the customers pom.xml and the profile `local` is also absent.

I have created a new README for that service and slightly modified the persistence.properties to make the service runnable locally.
Also created a maven wrapper for convenience and reproducibility.

Signed-off-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

### CODE REVIEW

**Review by rromannissen — COMMENTED** [review]
@HarikrishnanBalagopal thanks for your PR. The point of this application is to emulate a legacy application with many of the antipatterns present on old legacy applications. The end to end demo scenario for the Konveyor tools requires this application to use an Oracle database, as migrating the database itself is part of the actual demo. Because of that, I see no point in applying changes to the application to work with PostgreSQL since that would break the proposed scenario. To get more details about the context of this demo and the associated demo applications, you can [watch the recording available in YouTube](https://www.youtube.com/watch?v=aKDFFDXPHYk).

**Comment by HarikrishnanBalagopal** [comment]
@rromannissen Thanks for taking a look at the PR.
```
Because of that, I see no point in applying changes to the application to work with PostgreSQL since that would break the proposed scenario.
```
That's fine, my intention is not to replace the database but to get it running locally. The current instructions in the README simply give an error when executed. They don't let you run it with or without Oracle.

Would it make sense to have 2 application.properties file similar to the `Orders` service? One for local use with embedded H2 and another for Openshift use with Oracle?

**Comment by HarikrishnanBalagopal** [comment]
Unrelated to this, but there seems to be more bugs:
https://github.com/konveyor/mig-demo-apps/blob/master/apps/e2e-demo/orders/src/main/java/io/konveyor/demo/orders/controller/OrderController.java#L37
The `log` variable is not defined.

**Comment by HarikrishnanBalagopal** [comment]
Another bug, the Order service returns a list instead of a page
https://github.com/konveyor/mig-demo-apps/blob/master/apps/e2e-demo/orders/src/main/java/io/konveyor/demo/orders/controller/OrderController.java#L50-L51

It should return a page similar to the Customer service
https://github.com/konveyor/mig-demo-apps/blob/master/apps/e2e-demo/customers-tomcat-k8s/src/main/java/io/konveyor/demo/ordermanagement/controller/CustomerController.java#L36-L37

This is not a bug in `Orders` itself but during integration with the `Frontend` service, it breaks the website.
The website expects a page not a list.

**Comment by HarikrishnanBalagopal** [comment]
I will close this PR and open a new one later that makes the `customers` service build locally without changing the database that is used. Thanks for taking a look at this PR.

**Pull request closed without merging**
